version: '3.4'

services:
  myaspcoreapp:
    image: ${DOCKER_REGISTRY-}myaspcoreapp
    container_name: myaspcoreapp.app
    build:
      context: .
      dockerfile: MyAspCoreApp/Dockerfile
    hostname: myaspcoreapp.app
    networks:
      - myaspcoreapp_network

  myaspcoreapp.rabbitMq:
    image: "rabbitmq:3.7.17-management"
    container_name: myaspcoreapp.rabbitmq
    hostname: myaspcoreapp.rabbitmq
    networks:
      - myaspcoreapp_network

volumes:
  esdata:
    driver: local

networks:
  myaspcoreapp_network: